---
- name: Global Server Setup
  hosts: all
  roles:
    - root_ssh_keys
    - sshd

- name: Prod Setup
  hosts: prod
  roles:
    - nginx_site

- name: Dev Setup
  hosts: dev
  roles:
    - root_passwd
    - cowsay
    - nginx_site
